version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: main
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "EST"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependabot"
    commit-message:
      prefix: "(fix) update"
    ignore:
      dependency-name: "*"
      update-types: ["version-update:semver-major"]
