name: Generate website metrics
on:
  workflow_dispatch:
jobs:
  metrics:
    name: Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Detailed report
        uses: lowlighter/metrics@v3.19
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://kevinzunigacuellar.com
